name: dicoding_story_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  go_router: ^15.1.3
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
